"""Se agrega una atributo llamado descripcion

Revision ID: bf0cabd3244a
Revises: 2a61bba2dcae
Create Date: 2026-03-30 22:30:20.410930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf0cabd3244a'
down_revision: Union[str, Sequence[str], None] = '2a61bba2dcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'descripcion')
    # ### end Alembic commands ###
