"""Restriccion al campo nombre

Revision ID: d327febc9738
Revises: bf0cabd3244a
Create Date: 2026-03-31 19:44:16.395288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd327febc9738'
down_revision: Union[str, Sequence[str], None] = 'bf0cabd3244a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_producto_nombre'), 'producto', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_nombre'), table_name='producto')
    # ### end Alembic commands ###
